### ISSUE TITLE
[BUG]登录页面无法唤起键盘

### ISSUE THREAD

**Issue by mtcoafun** [EhPanda-Team/EhPanda#241]
点击输入帐号时键盘无法唤起

**Comment by mtcoafun** [comment]
需要重启一到两次才可解决

**Comment by mtcoafun** [comment]
并且在输入账号页面当账号输入错误时，点击空白处无法隐藏键盘

**Comment by tatsuz0u** [comment]
您好，請問方便錄製一段影片並開啟觸控區域顯示以判斷問題嗎？
可以透過輕點鍵盤上的 `Done` 鍵收起喔。

**Comment by mtcoafun** [comment]
是的，点击done的时候一直闪屏，是偶现的，现在没法录视频了
