### ISSUE TITLE
[BUG] 标签翻译不起作用

### ISSUE THREAD

**Issue by LawrenceLiuQuanzhou** [EhPanda-Team/EhPanda#248]
即使打开标签拓展，标签也没能翻译。
通过在 GitHub 上搜索，发现标签翻译应该引用自"EhTagTranslation" 这个项目：https://github.com/EhTagTranslation/Database
去那边看了也的确有提到可使用 EhPanda 使用EhTagTranslation 的翻译。
类似的软件，如 FEhViewer，则正常显示翻译。
我还注意到在“标签拓展”的选项下面，有个“导入自定义翻译”，所以我想：
1. 这是否是 Bug？如果是，希望能修复，如果不是，请告诉我哪里有什么没有设置正确。
2. 此处的“导入自定义翻译”该以什么格式、什么文件导入？或许我能基于上面的数据库，手动导入一个先用着。

**Comment by SunBrook** [comment]
@LawrenceLiuQuanzhou 
我今天刚好下载了这个软件，也是出现你说的问题，通过导入可以解决没有翻译的问题。

你可以如下操作：
1. 到这个发布界面直接用手机下载 db.text.json 文件，地址  https://github.com/EhTagTranslation/Database/releases/tag/v6.4246.1
![download](https://user-images.githubusercontent.com/14243713/165235368-d3acf64c-a36f-4d24-abd5-02a3fedfe0e9.png)
2. 打开软件 启用标签扩展，导入这个文件。导入之后打开翻译标签等选项，标签就都翻译出来了。
![settings](https://user-images.githubusercontent.com/14243713/165235599-af77861b-8dc0-4db7-be25-25038c7396fc.png)


可惜不能同步数据，这个库同步数据的频率太高了，目前

需要自己手动替换翻译json，主要我是不会写ios代码，不然就写个自动获取更新词库的功能了

**Comment by LawrenceLiuQuanzhou** [comment]
> @LawrenceLiuQuanzhou 我今天刚好下载了这个软件，也是出现你说的问题，通过导入可以解决没有翻译的问题。
> 
> 你可以如下操作：
> 
> 1. 到这个发布界面直接用手机下载 db.text.json 文件，地址  https://github.com/EhTagTranslation/Database/releases/tag/v6.4246.1
>    ![download](https://user-images.githubusercontent.com/14243713/165235368-d3acf64c-a36f-4d24-abd5-02a3fedfe0e9.png)
> 2. 打开软件 启用标签扩展，导入这个文件。导入之后打开翻译标签等选项，标签就都翻译出来了。
>    ![settings](https://user-images.githubusercontent.com/14243713/165235599-af77861b-8dc0-4db7-be25-25038c7396fc.png)
> 
> 可惜不能同步数据，这个库同步数据的频率太高了，目前
> 
> 需要自己手动替换翻译json，主要我是不会写ios代码，不然就写个自动获取更新词库的功能了

Wonderful！🎉🎉🎉

**Comment by tatsuz0u** [comment]
您好。
這應該是因為您的網路環境無法取得資料庫內容，一個 CDN 功能應該可以處理。
至於格式可以參考上述回覆，謝謝 @SunBrook。

**Comment by tatsuz0u** [comment]
@chihchy plz close it if no response from issuer in 1d.
