### ISSUE TITLE
AltStore源不受支持

### ISSUE THREAD

**Issue by CaliInn-Li** [EhPanda-Team/EhPanda#249]
效果如图：
![image](https://user-images.githubusercontent.com/40906144/167281589-a0184770-4868-48cc-9f42-93c36a1bc8c3.png)

## 版本信息
ehpanda 2.4.0(136)
AltStore 1.5

**Comment by tatsuz0u** [comment]
@chihchy plz close it since someone else has answered the question.

**Comment by AjianYo** [comment]
> altstore目前只有捐赠的测试版支持添加自定义源 可以尝试mitm重定向其信任的源到ehpanda
> 
> ```
> [URL Rewrite]
> https://altstore.oatmealdome.me/ https://raw.githubusercontent.com/EhPanda-Team/EhPanda/main/AltStore.json header
> 
> [MITM]
> hostname = %APPEND% altstore.oatmealdome.me
> ```

我把这段写入到iOS15.7 shadowrocket 2.2.28 的配置文件.conf中，确保解密https解密打开且证书信任，依然无效。altstore 1.6.3，请问我应该如何解决

**Comment by tatsuz0u** [comment]
@AjianYo 可以考慮等待 AltStore 2.0 發佈喔，我記得它會給非測試用戶也提供這個功能。

**Comment by AjianYo** [comment]
> @AjianYo 可以考慮等待 AltStore 2.0 發佈喔，我記得它會給非測試用戶也提供這個功能。

好的，谢谢
