### ISSUE TITLE
[BUG]SNI没有起到作用，所有的东西加载都非常的慢

### ISSUE THREAD

**Issue by ukcr** [EhPanda-Team/EhPanda#261]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Device: [e.g. iPhone 12]
 - OS: [e.g. iOS 15]
 - App Version [e.g. 1.0.3]

**Additional context**

**Comment by tatsuz0u** [comment]
您好。繞過 SNI 阻斷功能不能保證您能夠正常或順暢地瀏覽，仍然受網路環境影響。

**Comment by tatsuz0u** [comment]
@chihchy please close it if no response from the issuer in 1d.
