### ISSUE TITLE
[BUG] 快速搜索关键词编辑中，中文输入法无法使用 Chinese IME does not work in quick search keyword editor

### ISSUE THREAD

**Issue by Butanediol** [EhPanda-Team/EhPanda#262]
**Describe the bug**
在快速搜索中编辑关键词，中文输入法无法上词，或卡死。

**To Reproduce**
1. 打开快速搜索
2. 添加快速搜索关键词
3. 使用中文输入法在名称中输入
4. 中文输入法异常上词或卡死

**Expected behavior**
中文输入法正常上词

**Screenshots**
[Screenshot](https://i.imgur.com/gy11vM7)

**Please complete the following information:**
 - Device: iPhone 12, iPhone 12 Simulator, iPad Pro 11-inch
 - OS: iOS 15.5
 - App Version latest release & master branch

**Additional context**

https://github.com/EhPanda-Team/EhPanda/pull/263

猜测是 TCA 的 Binding 导致 TextField 出现问题，临时使用了一个比较简陋的方式修复。

**Comment by tatsuz0u** [comment]
您好。
經測試在

- iOS 16.0
- iPhone X
- Xcode 14.0.1 build 

環境下

- 中文注音
- 中文拼音
- 日文

正常。

建議您更新至 iOS 16.0 並等待新版本發佈修復。

@chihchy fixed in #275.
