### ISSUE TITLE
[BUG]ios16 beta5安装不上

### ISSUE THREAD

**Issue by jsbzukab** [EhPanda-Team/EhPanda#270]
我的ios15.5的iPhone11pm用sideloadly可以装上并正常使用,ios16.0 beta 5安装时手机显示无法验证其完整性

**Comment by taoyeh** [comment]
老哥你好，我是这方面的萌新，想想你请教，你有什么好的方法把ipa文件装到iphone上的，谢谢老哥指点我 = v =

**Comment by tatsuz0u** [comment]
@chihchy #250 duplicated.
