### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MRBXC** [EhPanda-Team/EhPanda#272]
**Describe the bug**
When you enter the main screen of this app and then click some of those reference comic, the content of that comic can be loaded incorrectly. To be more clearly, the shown comic is not consistent with the title page.

**To Reproduce**
1. Open the app and get in to main screen
2. Click the comic randomly 
3. You may see the bug

**Please complete the following information:**
 - Device: iPhone 13 Pro Max
 - OS: iOS 16 beta 6
 - App Version: latest version

**Comment by tatsuz0u** [comment]
@chihchy fixed in #275.
