### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by MoroboshiKirari** [EhPanda-Team/EhPanda#274]
Hello, Does the 'Download to Gallery or File' feature support?

Thank you

**Comment by tatsuz0u** [comment]
Yes and no.
You can save an image to photo library by
- Long-press the image 
- Tap the save / save original button

For `Download to file`, currently there is no download feature in EhPanda.

**Comment by tatsuz0u** [comment]
@chihchy plz close it if no response from issuer in 1d.

**Comment by MoroboshiKirari** [comment]
> Yes and no.
> 
> You can save an image to photo library by
> 
> 1. Long-press the image 
> 
> 2. Tap `Save` / `Save original`
> 
> 
> 
> For `Download to file`, currently there is no download feature in EhPanda.

Is there still no function to download the entire image of the work?
