### ISSUE TITLE
v 2.4.2 marked as Trojan:Script/Wacatac.H!ml

### ISSUE THREAD

**Issue by ShiguFox1992** [EhPanda-Team/EhPanda#281]

**Comment by tatsuz0u** [comment]
Any details?

cc @chihchy 
Please close this issue if no response from the issuer in 1d.

**Comment by ShiguFox1992** [comment]
It was flagged as a Trojan by Windows Security under Trojan:Script/Wacatac.H!ml
even the previous version was flagged and removed by it

**Comment by tatsuz0u** [comment]
Thanks for your feedback.
But I have no idea why Windows Defender flagged EhPanda.ipa as a trojan.
It should be fine since its source code can be reviewed by anyone and it's built & released by GitHub Actions.
Maybe Windows Defender considered an unsigned ipa file as a threat?

**Comment by ShiguFox1992** [comment]
Yeah, and it deleted it without waiting as well
