### ISSUE TITLE
[Feature Request] Will there be ios16.1

### ISSUE THREAD

**Issue by gyhqwe** [EhPanda-Team/EhPanda#289]
Will there be ios16

**Comment by gyhqwe** [comment]
Accidentally updated😭

**Comment by tatsuz0u** [comment]
I'm not sure what did you mean by "Will there be iOS 16.1". 🤔
iOS 16.1 has been released and I don't think it's relevant to EhPanda.

cc @chihchy Please close this issue if no response from the issuer in 1d.
