### ISSUE TITLE
搜索闪退

### ISSUE THREAD

**Issue by lsqzby** [EhPanda-Team/EhPanda#296]
用中文搜索时，最新版应用闪退，ipados16

**Comment by tatsuz0u** [comment]
您好。感謝您的回報。

但在下述裝置上測試並未能重現您描述的問題。
可以提供重現步驟或從啟動 App 至崩潰的螢幕錄影嗎？
- iPad mini 6
- iPadOS 16.1.1
- EhPanda v2.5.0

cc @chihchy Please close this issue if no response from the issuer in 1d.
