### ISSUE TITLE
图片浏览问题

### ISSUE THREAD

**Issue by LO-FANG** [EhPanda-Team/EhPanda#325]
放大图片突然变成了整个屏幕内内容放大，之前用的是单张图片在它所在的框内放大，其他图片不受影响，不知道是不是我开了什么设置导致的情况

**Comment by tatsuz0u** [comment]
您好，感謝您的回報。
雖然不確定是在哪個版本發生的改動，但這個效果是有意為之的。這更符合我們想提供的使用體驗。

**Comment by tatsuz0u** [comment]
Please close this issue. @chihchy
