### ISSUE TITLE
[BUG]发生了解析错误请稍后再试

### ISSUE THREAD

**Issue by yangfyustc** [EhPanda-Team/EhPanda#345]
**Describe the bug**
主页、搜索、收藏主界面可正常打开并展示预览图，打开画廊提示“发生了解析错误请稍后再试”。

开启VPN（使用来自monocloud提供的服务）、开启与关闭“实验室-域前置绕过SNI阻断”功能、重新登陆账号均无法显示。

**Please complete the following information:**
 - Device: [iPhone 12]
 - OS: [e.g. iOS 16.1.1]
 - App Version [e.g. 2.7.1]

**Additional context**
我的账号没有exhentai权限，igneous为mystery，但前几天在2.5.1版本的ehpanda可以正常使用，于2023.09.08晚出现该BUG。

**Comment by tatsuz0u** [comment]
您好，2.7.2 版本已解決該問題，請考慮更新。

**Comment by yangfyustc** [comment]
> 您好，2.7.2 版本已解決該問題，請考慮更新。

2.7.2版本已解决问题，麻烦了。

出现bug的时候也从2.5.1版本更新到了当时最新版本2.7.1，当时2.7.2还没发布，以为是我自己网络状况问题。

今天提交这个issue的时候没注意到发布了新版本，十分抱歉！
