### ISSUE TITLE
[BUG] Unable to read most of the content in EX source

### ISSUE THREAD

**Issue by WhiteColloid** [EhPanda-Team/EhPanda#387]
**Describe the bug**
In ex source, I can see covers of the manga, but I when I click most of them, it returns me an error page: 网页解析器发生故障（Web parser failure）. I can't access any manga from 'Favorite' section either. 
Only some manga from 'Ranking'（排行）section  in the front page can load properly

**To Reproduce**
1. Go to 'Settings'（设定） -> ‘Account'（账号）
2. Log in  and Click on 'ExHentai'
3. Exit Settings page
4. Click on any manga's cover on the front page and see the error

**Expected behavior**
See the content of manga (like the EH source do)

**Screenshots**
Here is the error message:
![Clip_2024-10-27_12-16-00](https://github.com/user-attachments/assets/3a16617d-9cfb-4f83-b812-c1aa5b945494)

**Please complete the following information:**
 - Device: iPad Pro (12.9inch) - 5th generation
 - OS: iPad OS 18.0.1
 - App Version: 2.7.6

**Additional context**
I tried changing different proxies and the error persists

**Comment by M0rtale** [comment]
+1 Error when parsing preview, see log below

![image](https://github.com/user-attachments/assets/ded36a71-b2b1-4cd8-b4a4-0f1d1e899e98)

**Comment by WhiteColloid** [comment]
Refer to #388: After change the Thumbnail Settings - Size to Normal, I can see the info of manga by clicking the cover of it. However, when I click the 'read' button, the app can't load the pictures. (there are also no thumbnails showing a preview of the manga). Here is the error page:
![IMG_7357(1)](https://github.com/user-attachments/assets/9da02f4f-2a1a-4b36-a4ce-7f64e1a74aab)

**Comment by vvbbnn00** [comment]
@WhiteColloid 
Could you please try setting ehSetting's Gallery Page Thumbnail Labeling (画廊页面缩略图标签) - Show label below gallery thumbnails (在画廊缩略图下方显示标签) to None (不显示) and then check if the issue still exists?

**Comment by WhiteColloid** [comment]
> @WhiteColloid Could you please try setting ehSetting's Gallery Page Thumbnail Labeling (画廊页面缩略图标签) - Show label below gallery thumbnails (在画廊缩略图下方显示标签) to None (不显示) and then check if the issue still exists?
It works now. Thank you.

**Comment by vvbbnn00** [comment]
@WhiteColloid 
Thank you for your feedback. I have identified the issue and will submit a new Pull Request to address it.
