### ISSUE TITLE
[BUG] Crash on iOS 16.5

### ISSUE THREAD

**Issue by GEEKiDoS** [EhPanda-Team/EhPanda#400]
**Describe the bug**
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/Volumes\/VOLUME\/*\/libswiftObservation.dylib","Referenced from: <9622156D-DAAD-36E2-89DB-427BE6F7F001> \/Volumes\/VOLUME\/*\/EhPanda.app\/EhPanda (built for iOS 17.0 which is newer than running OS)","Reason: tried: '\/Volumes\/VOLUME\/*\/libswiftObservation.dylib' (no such file), '\/private\/preboot\/Cryptexes\/OS\/Volumes\/VOLUME\/*\/libswiftObservation.dylib' (no such file), '\/Volumes\/VOLUME\/*\/libswiftObservation.dylib' (no such file, not in dyld cache)"]},
 
**Please complete the following information:**
 - Device: iPhone 13 mini
 - OS: iOS 16.5
 - App Version 2.7.8

**Comment by GEEKiDoS** [comment]
Closed as I did not saw system requirement

**Comment by GEEKiDoS** [comment]
I backported 2.7.8 to 2.7.5...
https://github.com/GEEKiDoS/EhPanda/actions/runs/12069397980/artifacts/2249760952
hopefully it helps

**Comment by wileney** [comment]
> 谢谢大佬 你是我的神！

2.7.5会解析失败如何解决？

**Comment by GEEKiDoS** [comment]
> > 谢谢大佬 你是我的神！
> 
> 2.7.5会解析失败如何解决？

如果最新版能用的话 再backport源码回来就可以了
